services:
  database:
    image: 'postgres:latest'
    ports:
      - 15432:5432
    environment:
        - POSTGRES_DB=face
        - POSTGRES_USER=face
        - POSTGRES_PASSWORD=face
    networks:
      - postgres-network
    volumes:
      - postgres-data:/var/lib/postgresql/data/

  # ngrok:
  #   image: 'ngrok/ngrok:latest'
  #   environment:
  #     - NGROK_AUTHTOKEN=
  #   command:
  #     - "http"
  #     - "http://host.docker.internal:5050"
  #   ports:
  #     - 4040:4040

  # service:
  #   build: .
  #   env_file: .env
  #   ports:
  #     - 5050:5050

networks: 
  postgres-network:

volumes:
  postgres-data: {}
